# Generated by Django 5.1.5 on 2025-01-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("release_date", models.DateField()),
                ("duration", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("poster", models.ImageField(upload_to="posters/")),
                ("trailer_url", models.URLField(blank=True, null=True)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=2)),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "cast",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.actor"
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.genre"
                    ),
                ),
                (
                    "language",
                    models.ManyToManyField(related_name="movies", to="movies.language"),
                ),
            ],
        ),
    ]
