# Generated by Django 5.1.5 on 2025-01-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="language",
            name="code",
        ),
    ]
