# Generated by Django 5.1.5 on 2025-12-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_remove_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="rating",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
