# Generated by Django 5.1.5 on 2025-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_movies_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
