# Generated by Django 5.1.5 on 2026-05-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movies_poster_alter_movies_trailer_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
