# Generated by Django 5.1.5 on 2026-06-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_movies_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="movies",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movies",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
