# Generated by Django 5.1.5 on 2026-06-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_movies_is_active_movies_is_archived_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="movies",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="movies",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("archived", "Archived"),
                    ("deleted", "Deleted"),
                ],
                default="active",
            ),
        ),
    ]
