# Generated by Django 5.1.5 on 2026-07-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_remove_movies_is_active_remove_movies_is_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="quantity",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
