# Generated by Django 5.1.5 on 2025-12-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_alter_movies_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
