# Generated by Django 5.1.5 on 2025-12-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_alter_movies_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movies",
            name="poster",
            field=models.ImageField(max_length=255, upload_to="posters/"),
        ),
        migrations.AlterField(
            model_name="movies",
            name="trailer_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
